### PR TITLE
#845: Return unknown previous block when the parent node is not final…

### LINKED ISSUE #845: [BUG]: Could not create state node
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Occasionally chain will log that it could not create new state node.

While working on p2p, I found that this message was being logged when a child block was attempting to be applied while the parent block is being applied. This leads to a race condition that can result in timeouts within p2p. The race condition is not good in chain either.

When the parent block is being finalized, we release all locks and request a unique lock in order to bump head block, fork heads, and LIB atomically. When creating a new state node, state db waits for the parent node to be finalized, holding a lock while it does. Thankfully, creating a state node does use an internal timeout otherwise this would result in a complete deadlock of the node.

### Expected behavior

We should detect this condition and return a meaningful error. I suggest `unknown_previous_block` for two reasons.

1. p2p is already handling this error and will attempt to re-apply the block when the parent is applied.
2. Internal to chain, this creates a consistent definition for the error. We only know of a block once it has been successfully applied. The error in this case makes sense because the parent node has not yet finished applying, therefore the previous block is unknown.

### Steps to reproduce

_No response_

### Environment

```markdown
- OS:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by mvandeberg**
…ized

Resolves #845

## Brief description

Returns `unknown_previous_block` error when the parent node is not finalized. The prevents a deadlock when the parent node is trying to finalize and the child node is waiting on the parent node to finalize to create a state node.

Branch is not passing CI because it is not based on `latest` and therefore fails the `pending_nonce` integration test. This is expected. The branch is good otherwise and is running in dev.

## Checklist

- [X] I have built this pull request locally
- [X] I have ran the unit tests locally
- [X] I have manually tested this pull request
- [X] I have reviewed my pull request
- [X] I have added any relevant tests

### CODE REVIEW

File: src/koinos/chain/controller.cpp [hunk 1]
```diff
@@ -322,6 +322,8 @@ apply_block_result controller_impl::apply_block( const protocol::block& block, c
     KOINOS_ASSERT( block_id == root->id(), unknown_previous_block_exception, "unknown previous block" );
     return {}; // Block is current LIB
   }
+  else
+    KOINOS_ASSERT( parent_node->is_finalized(), unknown_previous_block_exception, "unknown previous block" );
```
Comment (sgerbino) [inline src/koinos/chain/controller.cpp:326]: If the `if` uses braces we should use braces in the `else`

Comment (sgerbino) [reply src/koinos/chain/controller.cpp:326]: Also, it appears there's an integration failure

Comment (mvandeberg) [reply src/koinos/chain/controller.cpp:327]: It fails the integration test because the branch was based on a commit prior to the nonce changes. I built the image manually and pushed it for testing p2p without all of the nonce code.

I can merge master in to the branch to pass integration tests, but then I cannot test it on its own with p2p.

**Review by sgerbino — APPROVED** [review]
